esphome:
  name: $esphome_name

esp32:
  board: esp32dev

# Enable logging
logger:
  # level: VERY_VERBOSE

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    password: !secret ap_password

captive_portal:
    
mqtt:
  broker: !secret mqtt_broker
  username: !secret mqtt_username
  password: !secret mqtt_password
  discovery: True
  discover_ip: True 

light:
  - platform: neopixelbus
    id: led
    variant: WS2812X
    pin: GPIO13
    num_leds: 1
    restore_mode: ALWAYS_ON

i2c:

bme68x_bsec2_i2c:
  address: 0x77
  model: bme680
  operating_age: 28d
  sample_rate: LP
  supply_voltage: 3.3V

sensor:
  - platform: bme68x_bsec2
    temperature:
      name: "BME680 Temperature"
    pressure:
      name: "BME680 Pressure"
    humidity:
      name: "BME680 Humidity"
    iaq:
      name: "BME680 IAQ"
      id: iaq
    co2_equivalent:
      name: "BME680 CO2 Equivalent"
    breath_voc_equivalent:
      name: "BME680 Breath VOC Equivalent"

text_sensor:
  - platform: bme68x_bsec2
    iaq_accuracy:
      name: "BME680 IAQ Accuracy"

  - platform: template
    name: "BME680 IAQ Classification"
    icon: "mdi:checkbox-marked-circle-outline"
    lambda: |-
      auto l = id(led).turn_on().set_brightness(1.0);
      auto aiq = "";     
      if ( int(id(iaq).state) <= 50) {
        aiq = "Excellent";
        l.set_rgb(0.0, 1.0, 0.0);
      }
      else if (int(id(iaq).state) >= 51 && int(id(iaq).state) <= 100) {
        aiq = "Good";
        l.set_rgb(0.5, 1.0, 0.0);
      }
      else if (int(id(iaq).state) >= 101 && int(id(iaq).state) <= 150) {
        aiq = "Lightly polluted";
        l.set_rgb(1.0, 1.0, 0.0);
      }
      else if (int(id(iaq).state) >= 151 && int(id(iaq).state) <= 200) {
        aiq = "Moderately polluted";
        l.set_rgb(1.0, 0.5, 0.0);
      }
      else if (int(id(iaq).state) >= 201 && int(id(iaq).state) <= 250) {
        aiq = "Heavily polluted";
        l.set_rgb(1.0, 0.0, 0.0);
      }
      else if (int(id(iaq).state) >= 251 && int(id(iaq).state) <= 350) {
        aiq = "Severely polluted";
        l.set_rgb(1.0, 0.0, 0.0);
      }
      else if (int(id(iaq).state) >= 351) {
        aiq =  "Extremely polluted";
        l.set_rgb(1.0, 0.0, 0.0);
      }
      else {
        aiq = "error";
      }
      l.perform();
      return {aiq};